import { compareTexts } from '@/features/comparison/similarity';
export type ReviewStatus = 'Needs review' | 'Investigating' | 'Resolved';
export interface ExamCase { id: string; subject: string; title: string; source: string; sourceType: string; timestamp: string; status: ReviewStatus; original: string; suspected: string; score: number }
const mathematics = 'Section A: Differential Calculus\n\n1. Find the derivative of the function f(x) = x squared plus three x minus five. Show all steps in your working.\n\n2. Evaluate the definite integral of two x plus one between zero and four. Interpret your result geometrically.\n\n3. A rectangular enclosure has a perimeter of forty metres. Determine the dimensions that maximize its area and justify your answer.';
const rows = [
  { id: 'EG-2026-041', subject: 'Mathematics', title: 'Calculus · Semester II', source: 'Telegram', sourceType: 'Public study channel', timestamp: '2026-10-08T09:42:00Z', status: 'Needs review' as const, original: mathematics, suspected: mathematics.replace('Section A: Differential Calculus', 'Tomorrow’s mathematics questions').replace('Interpret your result geometrically.', 'Draw a diagram for your answer.').replace('and justify your answer', 'with a clear explanation') },
  { id: 'EG-2026-040', subject: 'Physics', title: 'Mechanics · Semester I', source: 'WhatsApp', sourceType: 'Submitted screenshot transcript', timestamp: '2026-10-08T08:16:00Z', status: 'Investigating' as const, original: 'A particle of mass two kilograms moves under a constant force of ten newtons. Calculate its acceleration and the distance travelled in five seconds starting from rest. Explain the principle of conservation of momentum with a suitable example. Derive the expression for the kinetic energy of a moving body.', suspected: 'Physics exam preparation. A particle of mass two kilograms moves under a constant force of ten newtons. Calculate its acceleration and the distance travelled in five seconds starting from rest. Explain the principle of conservation of momentum with a suitable example. Discuss circular motion and gravitational fields.' },
  { id: 'EG-2026-039', subject: 'Computer Science', title: 'Data structures · Semester III', source: 'Discord', sourceType: 'Public discussion thread', timestamp: '2026-10-07T15:30:00Z', status: 'Needs review' as const, original: 'Explain the difference between a stack and a queue with examples. Implement a binary search tree and describe the time complexity of insertion and deletion. Compare breadth first search and depth first search for graph traversal. Discuss the advantages of a hash table over a linked list.', suspected: 'Implement a binary search tree and describe the time complexity of insertion and deletion. Compare breadth first search and depth first search for graph traversal. Write a program for sorting an array using merge sort. Describe the memory requirements of recursive algorithms.' },
  { id: 'EG-2026-038', subject: 'Chemistry', title: 'Organic chemistry · Semester II', source: 'Telegram', sourceType: 'Public study channel', timestamp: '2026-10-07T11:05:00Z', status: 'Resolved' as const, original: 'Describe the mechanism of electrophilic aromatic substitution in benzene. Explain the role of a catalyst in the nitration reaction. Compare the acidity of phenol and ethanol with reference to resonance stabilization. Draw the structures of the products formed during oxidation of primary alcohols.', suspected: 'Chemistry revision notes. Describe the mechanism of electrophilic aromatic substitution in benzene. Explain the role of a catalyst in the nitration reaction. Read about chemical bonding and the periodic table. Practice calculations involving molar concentrations and gas laws.' },
  { id: 'EG-2026-037', subject: 'Economics', title: 'Macroeconomics · Semester IV', source: 'Reddit', sourceType: 'Public forum post', timestamp: '2026-10-06T13:20:00Z', status: 'Investigating' as const, original: 'Define gross domestic product and explain the expenditure approach to its measurement. Analyze the relationship between inflation and unemployment using the Phillips curve. Discuss the tools available to a central bank for controlling money supply.', suspected: 'Analyze the relationship between inflation and unemployment using the Phillips curve. Discuss the tools available to a central bank for controlling money supply. Explain how international trade influences domestic economic growth.' },
  { id: 'EG-2026-036', subject: 'Biology', title: 'Cell biology · Semester I', source: 'WhatsApp', sourceType: 'Submitted message transcript', timestamp: '2026-10-06T07:50:00Z', status: 'Resolved' as const, original: 'Describe the structure and function of the cell membrane. Explain the stages of mitosis with labelled diagrams. Compare aerobic and anaerobic respiration. Discuss the role of ribosomes in protein synthesis.', suspected: 'Describe the structure and function of the cell membrane. Explain the stages of mitosis with labelled diagrams. Study the classification of plants and the anatomy of flowering plants. Review ecological food chains and energy transfer.' },
];
export const demoCases: ExamCase[] = rows.map(row => ({ ...row, score: compareTexts(row.original, row.suspected).score }));
export function formatTimestamp(timestamp: string) { return new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit', timeZone: 'UTC' }).format(new Date(timestamp)); }
